sudo: false

language: java

cache:
  directories:
   - $HOME/.m2

jdk:
  - oraclejdk8

env:
  global:
   - DISPLAY=:99.0

before_install:
  - sh -e /etc/init.d/xvfb start - sleep 10

before_script:
  - cd org.eclipse.papyrus-informationmodeling.build.tycho

script:
  - cd org.eclipse.papyrus-informationmodeling.build.tycho
  - mvn clean install -Pproduct
