sudo: false

language: java

cache:
  directories:
   - $HOME/.m2

jdk:
  - oraclejdk8

env:
  global:
   - DISPLAY=:99.0

before_install:
  - sh -e /etc/init.d/xvfb start - sleep 10

script:
  - mvn clean install -Pproduct
